version: "3.8"
services:
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - todolist-db:/var/lib/postgresql/data
  todolistserver:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  todolist-db:
